// @ts-check
/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

export default {
  // Autogenerated sidebar from the .md metadata (in the header) parameters
  documentationSidebar: [{type: 'autogenerated', dirName: '.'}],
};
